### ISSUE TITLE
Can't get the ARK server to run

### ISSUE THREAD

**Issue by problemss** [thmhoag/arkserver#19]
I am running this container on a Mac.

This is my run command:
`docker run -d -v /opt/docker/Steam:/home/steam/Steam -v /opt/docker/Ark:/ark -p 27015:27015 -p 27015:27015/udp -p 7778:7778 -p 7778:7778/udp -p 7777:7777 -p 7777:7777/udp -e am_ark_SessionName='#####' -e am_ark_ServerPassword='#####' -e am_ark_ServerAdminPassword='#####' --restart unless-stopped --name ark thmhoag/arkserver`

When I run 'docker exec ark arkmanager status' it says the server is not running and says that '/ark/server/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini' is missing.

The folder structure was automatically created under /opt/docker/Ark, but when I navigate to '/opt/docker/Ark/server/ShooterGame/Saved/Config/LinuxServer/' it is empty.

I have a feeling this is a user error and probably pretty obvious, but I haven't been able to figure it out. Any help?

**Comment by TheInternetIsReal** [comment]
I'm running into a similar problem. I ran the container for the first time like so:
`docker run -d -v /ark/ark-server-disk/steam:/home/steam/Steam -v /ark/ark-server-disk/:/ark -p 27015:27015 -p 27015:27015/udp -p 7778:7778 -p 7778:7778/udp -p 7777:7777 -p 7777:7777/udp thmhoag/arkserver`
And there are no server files at all:
```
user@ark-server:~$ ls /ark/ark-server-disk/server/ShooterGame/Binaries/Linux/
user@ark-server:~$ 
```
When I run the arkmanager status command I get this:
```
user@ark-server:~$ sudo docker exec gracious_wilbur arkmanager status
Running command 'status' for instance 'main'
[  WARN  ]      Your ARK server exec could not be found.
 Server running:   No 
/usr/local/bin/arkmanager: line 369: /ark/server/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini: No such file or directory
/usr/local/bin/arkmanager: line 369: /ark/server/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini: No such file or directory
 Server listening:   No 
 Server build ID:   
```
Did I do something wrong or is this container broken? The instruction for TuRz4m/Ark-docker were much better, espeically for the first run. I also have no idea how I'm supposed to set the "required environment variables" and if the game config files override those or not.

**Comment by TheInternetIsReal** [comment]
Actually, it looks like the app ID for Ark was changed 2 days ago from 356110 to 376030: https://steamdb.info/app/376030/

**Comment by problemss** [comment]
@TheInternetIsReal I ended up running the install, 'docker exec ark arkmanager install' and all looks to be installed now. I thought this package didn't need that, but I must have been confused.

I did have to reboot it after the install finished, I thought it failed, but after coming back to it when several hours passed I was pleasantly surprised the server was running.
