### ISSUE TITLE
ark-server-tools update released v1.6.54

### ISSUE THREAD

**Issue by Ramblurr** [thmhoag/arkserver#20]
Many thanks for providing this image!

Just a friendly FYI that ark-server-tools has released an updated version: v.1.6.54

Normally I'd just wait to get the update without making an issue, but this release has a critical fix for servers that have epic players connecting like mine, namely https://github.com/arkmanager/ark-server-tools/commit/89e80dec9687849a010e9efac057a82c584efe86

Without this commit, the automatic restart script cannot detect when epic players are connected. So if only epic players are connected it will think there are zero players connected, resulting in an immediate restart.

My players have had this happen while flying or exploring in dangerous areas and lost all their stuff, so I'd like to get this release as soon as possible.

Again, many thanks!

**Comment by thmhoag** [comment]
Hey @Ramblurr, I've got a pending PR for this. As soon as the CI builds pass I will merge it and cut a release.

**Comment by thmhoag** [comment]
Hey @Ramblurr, this should be fixed, you'll want to pull `thmhoag/arkserver:v1.5.0`.
