### ISSUE TITLE
Steam Update Error crash

### ISSUE THREAD

**Issue by AvoMMH** [thmhoag/arkserver#23]
## Image Setup Details

* **Image Tag**: latest

* **Docker Host OS**: Ubuntu Server 16.04

* **`docker run` command or `docker-compose.yml` file**: 
$ docker run -d \
    -v steam:/home/steam/Steam \  # mounted so that workshop (mod) downloads are persisted
    -v ark:/ark \  # mounted as the directory to contain the server/backup/log/config files
    -p 27015:27015 -p 27015:27015/udp \  # steam query port
    -p 7778:7778 -p 7778:7778/udp \  # gameserver port
    -p 7777:7777 -p 7777:7777/udp \ # gameserver port
    --restart always
    thmhoag/arkserver

## Description of Issue

A few seconds after I start the  container it crashes with: Error! App '376030' state is 0x202 after update job.

I have nothing configured, I just downloaded the image and started it.

## Additional Information

Full Log:
```
###########################################################################
# Ark Server -  Fri Aug 28 10:32:54 UTC 2020
###########################################################################
Ensuring correct permissions...
Cleaning up any leftover arkmanager files...
Creating arkmanager.cfg from environment variables...
No game files found. Installing...
Starting cron service...
 * Starting periodic command scheduler cron
   ...done.
Loading crontab...
Save file validation is not enabled.
Backup on start is not enabled.
Running command 'start' for instance 'main'
[  WARN  ] 	Your ARK server exec could not be found.
Checking for updates before starting
Checking for update; PID: 43
sed: can't read /ark/server/steamapps/appmanifest_376030.acf: No such file or directory
Downloading ARK updateExecuting /home/steam/.steam/steamcmd/steamcmd.sh +@NoPromptForPassword 1 +login anonymous +force_install_dir /ark/staging +app_update 376030 +quit
Redirecting stderr to '/home/steam/.steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Warning: failed to init SDL thread priority manager: SDL not found
OK.
"@NoPromptForPassword" = "1"
Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) verifying install, progress: 8.80 (1135474594 / 12896302610)
 Update state (0x5) verifying install, progress: 13.22 (1704480165 / 12896302610)
 Update state (0x5) verifying install, progress: 15.43 (1990182830 / 12896302610)
 Update state (0x5) verifying install, progress: 83.05 (10710148050 / 12896302610)
 Update state (0x5) verifying install, progress: 85.90 (11077819081 / 12896302610)
 Update state (0x5) verifying install, progress: 98.79 (12740628701 / 12896302610)
Error! App '376030' state is 0x202 after update job.
Update download interrupted
The server is starting...
An update is currently in progress.  Start aborted
```

**Comment by catzoo** [comment]
After doing some searching, state 0x202 actually means out of space. I recommend seeing if you have enough space to install the server.

More info here: https://github.com/GameServerManagers/LinuxGSM/issues/1656

**Comment by thmhoag** [comment]
Thanks @catzoo, I suspect that is the case as well. However, I do think the repo's documentation could be a bit better around common issues like this, so I have added an issue to create an "FAQ" and "Common Issues" section in the repo wiki at some point down the line. 

Issue #24

**Comment by AvoMMH** [comment]
Thanks, that was the reason it woulnt start up.

But now I am having trouble joining from EpicGames Ark. Steam works fine but Epic players cant join.
I added the AM crossplatform flag, but it didnt work.

**Comment by AvoMMH** [comment]
nvm it just took some time to boot up
