### ISSUE TITLE
run.sh is too slow due to chown inherently taking a long time. 

### ISSUE THREAD

**Issue by michaeldelago** [thmhoag/arkserver#26]
## Image Setup Details

* **Image Tag**: Latest

* **Docker Host OS**: Ubuntu

* **`docker run` command or `docker-compose.yml` file**: Kubernetes Manifest, not relevant

## Description of Issue

the `run.sh` file uses `sudo chown steam:steam -R /ark`, which is slow.

It should use `find -not -user steam -not -group steam -exec chown steam:steam -v {} \;

## Additional Information

To be fair, I am mounting the /ark directory over NFS.

**Comment by thmhoag** [comment]
Merged and should now be included in the `:1.6.0` tag of the image. Thanks!
