### ISSUE TITLE
GameUserSettings.ini

### ISSUE THREAD

**Issue by jkread** [thmhoag/arkserver#33]
## Image Setup Details

version: '2'
services:
  ark:
    image: thmhoag/arkserver
    container_name: ark
    network_mode: bridge
    restart: always
    ports:
      - 7777:7777
      - 7777:7777/udp
      - 7778:7778
      - 7778:7778/udp
      - 27015:27015
      - 27015:27015/udp
    volumes:
      - ark:/ark
      - ark-steam:/home/steam
    environment:
      - TZ=America/Chicago
      - am_ark_SessionName=redac
      - am_serverMap=TheIsland
      - am_ark_ServerPassword=redac
      - am_ark_ServerAdminPassword=redac
      - am_ark_MaxPlayers=1
      - am_ark_QueryPort=27015
      - am_ark_Port=7778
      - am_ark_RCONPort=32330
      - am_arkwarnminutes=15
      - am_arkAutoUpdateOnStart=true
      - am_arkBackupPreUpdate=true
      - am_arkMaxBackupSizeMB=500
      - am_arkflag_crossplay=false
      - am_arkflag_NoBattlEye=true
      - am_ark_GameModIds=111111111,566885854,731604991,761535755,821530042,889745138,1404697612
     
## Description of Issue
Where do I place an edited copy of GameUserSettings.ini so that is gets loaded?  I've tried /ark/config/, ark/server/ShooterGame/config/ and neither work. Can't find anywhere else to put it.

**Comment by jkread** [comment]
I have now also tried

ark/server/ShooterGame/config/Linux/
ark/server/ShooterGame/config/LinusServer/

based on Issues on the Ark Server Tools github with no luck.

**Comment by jkread** [comment]
For historical and hysterical purposes the correct placement is 
/ark/server/ShooterGame/saved/config/LinusServer/GameUserSettings.ini

**Comment by tctfox** [comment]
> 
> 
> For historical and hysterical purposes the correct placement is
> /ark/server/ShooterGame/saved/config/LinusServer/GameUserSettings.ini

hei there
I was searching the GameUserSettings.ini too. So you just need to edit that file and it will edit the game values? I am a bit confused by the name "shooter game"

**Comment by jkread** [comment]
ShooterGame is the in-house name for the Ark Game.

I haven't gotten this to work 100%. Supposedly you can just put GameUserSettings.ini with you custom values in /ark/config and it will merger them when it build the file. Here is what mine looks like.  If you put them in /ark/server/ShooterGame/saved/config/LinusServer/GameUserSettings.ini it will work but get overwritten the next time the server builds.

https://pastebin.com/Td24Ku2E

**Comment by tctfox** [comment]
> ShooterGame is the in-house name for the Ark Game.
> 
> I haven't gotten this to work 100%. Supposedly you can just put GameUserSettings.ini with you custom values in /ark/config and it will merger them when it build the file. Here is what mine looks like. If you put them in /ark/server/ShooterGame/saved/config/LinusServer/GameUserSettings.ini it will work but get overwritten the next time the server builds.
> 
> https://pastebin.com/Td24Ku2E

Thanks! 
So just editing this file seems to work for you. A reply by the creator of the docker would be cool too

With "rebuild". Do you mean if you redeploy the container for example or also just a restart?
Cheers

**Comment by jkread** [comment]
I think even just a restart cause a script to run that overwrites it. I’ve tweaked mine quite a bit so working on rolling it back to test this more.

**Comment by tctfox** [comment]
> I think even just a restart cause a script to run that overwrites it. I’ve tweaked mine quite a bit so working on rolling it back to test this more.

That would defenitely be cool keep me posted. Having it resetting the game settings on every restart would be quite the big problem honestly. I need to find a solution to that before playing with my friends

**Comment by jkread** [comment]
Haven't verified yet as I need to wait a bit to redownload game files but line 93 of run.sh has the following so putting the GameUserSettings.ini in /ark/config should work.  As far as I can tell this repository is no longer active. I put in a fix to allow time zones to work correctly when passed in as an environment variable a month and it still hasn't been accepted or even acknowledged.  I have a fork (https://github.com/jkread/arkserver) jkread/arkserver on docker hub that currently only has that 1 enhancement but I am working on some others.

[ -f /ark/config/GameUserSettings.ini ] && ln -sf /ark/config/GameUserSettings.ini /ark/server/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini

**Comment by tctfox** [comment]
> Haven't verified yet as I need to wait a bit to redownload game files but line 93 of run.sh has the following so putting the GameUserSettings.ini in /ark/config should work. As far as I can tell this repository is no longer active. I put in a fix to allow time zones to work correctly when passed in as an environment variable a month and it still hasn't been accepted or even acknowledged. I have a fork (https://github.com/jkread/arkserver) jkread/arkserver on docker hub that currently only has that 1 enhancement but I am working on some others.
> 
> [ -f /ark/config/GameUserSettings.ini ] && ln -sf /ark/config/GameUserSettings.ini /ark/server/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini

Awesome dude thanks
Strange that those symlinks are even in the docker image here but somehow they wont get symlinked...
A docker compose for that image would be cool mate. 

Also like in another issue here on this github puid/guid variables for env would make a huge difference. It is probably really easily done if you use that user.sh file from the other image

**Comment by jkread** [comment]
I've added a docker compose sample to mine. I'll have to look at the puid/guid as I avoid those by using volumes instead of mounts. I'm still working on the gameusersettings.ini issue. I'll open issues for both over there tomorrow.

**Comment by tctfox** [comment]
> I've added a docker compose sample to mine. I'll have to look at the puid/guid as I avoid those by using volumes instead of mounts. I'm still working on the gameusersettings.ini issue. I'll open issues for both over there tomorrow.

Hei there thanks! 
Can I somehow message you? I got an issue wich if you want I would like to ask you about

It is an error I only get with your docker image. i think I spammed here enough already that's why I ask

**Comment by jkread** [comment]
Just go to https://github.com/jkread/arkserver and either open a new issue or use the discussion page.

By the way I have this GameUserSettings.ini thing fixed over there.

**Comment by thmhoag** [comment]
@jkread Sorry for the delay, I haven't been able to take the time to maintain this repo very well in the last few months. 

To clarify the intended functionality, the `/ark/config` folder is where this config file should go. For better or worse, that file structure was _supposed_ to make it easier to add in configs instead of having to deal with knowing the full path in the ShooterGame directory. As you've discovered, a symlink should be created on startup of the image and the config _should_ be loaded that way. 

I haven't experienced any issues with this on my own servers but if this is still causing a problem for you or for @tctfox I'm happy to re-open this and look into it.
