### ISSUE TITLE
Add a uid/gid environment variable option

### ISSUE THREAD

**Issue by Laynezilla** [thmhoag/arkserver#35]
## Description of Issue
It would be useful to be able to run this container as a different user. Something like [this](https://github.com/TuRz4m/Ark-docker/blob/master/user.sh) would work fine.

**Comment by tctfox** [comment]
> ## Description of Issue
> 
> It would be useful to be able to run this container as a different user. Something like [this](https://github.com/TuRz4m/Ark-docker/blob/master/user.sh) would work fine.

Yes this is true. I run into some issues earlier and another image that has puid etc values worked fine..

**Comment by jkread** [comment]
I've taken up this issue in my fork. I've already found where the script does not correctly update ownership. If there are still reasons to add environment variable support I will look at it.

https://github.com/jkread/arkserver

**Comment by thmhoag** [comment]
Sorry for the delay on this @Laynezilla. Agreed this would be a valuable add. Going to mark this issue properly so it doesn't get closed by the bot. Operating with a different user hasn't been well tested to date.
