### ISSUE TITLE
Game.ini

### ISSUE THREAD

**Issue by molnarviktor86** [thmhoag/arkserver#36]
Hi,

It seems like the gameusersettings.ini are applied on my dedicated server, but no matter what I do the Game.ini changes are just not working.

[/script/shootergame.shootergamemode]
MatingIntervalMultiplier=0.1
EggHatchSpeedMultiplier=20
BabyMatureSpeedMultiplier=10
BabyCuddleIntervalMultiplier=0.1

What am I missing here? FezVrasta's configuration parameter's again point to changes that has to put in gameusersettings.ini

**Comment by DrPsychick** [comment]
@molnarviktor86 : did you try writing the section case sensitive?
`[/Script/ShooterGame.ShooterGameMode]`

**Comment by thmhoag** [comment]
@molnarviktor86 Were you able to get this to work? I haven't experienced any issues getting the Game.ini file to load properly on my own servers, but I'm happy to take a closer look if you're still experiencing the issue.
