### ISSUE TITLE
Cannot update server version, nor can I use arkmanager. Requesting assistance.

### ISSUE THREAD

**Issue by BlakeNoel** [thmhoag/arkserver#49]
I've been running the image for about a month before I noticed that folks are unable to connect to the server. They told me I need to update the server version as the client has recently been updated. Here's the script I use to bring up the container (note that I substituted the password information with `*`, but they are valid strings):

```
#!/bin/bash

ARK=blakebot_ark

docker stop $ARK

docker rm $ARK

docker run -d \
  --name $ARK \
  -v /home/bnoel/docker_volumes/ark3:/app \
  -v /home/bnoel/docker_volumes/ark3_backups:/home/steam/ARK-Backups \
  --restart always \
  -p 27015:27015/udp \
  -p 7777:7777/udp \
  -p 7778:7778/udp \
  -e SESSION_NAME=blakebot \
  -e SERVER_PASSWORD=* \
  -e ADMIN_PASSWORD=* \
  hermsi/ark-server:latest
```

When looking through the documentation of this project, I'm led to believe that to update this server, I should be using arkmanager. Attempts to do so look like the following:

```
sudo docker exec blakebot_ark arkmanager
Invalid steamcmd_user in config file
```

The error seems obvious, but I'm unsure how to resolve the issue. Currently, this `steamcmd_user` in config file is default as is within this container... Specifically within `~/arkmanager/arkmanager.cfg` the related line looks like the following: `steamcmd_user="${STEAM_USER}"                                       # name of the system user who own steamcmd folder`.

Finally, here's the docker logs for the container, if you'd like to see anything or lack thereof (once again, passwords have been substituted with `*`):

```
sudo docker logs blakebot_ark
Starting periodic command scheduler: cron.
_______________________________________

# Ark Server - Sat Oct  8 23:57:07 UTC 2022
# IMAGE_VERSION: '1662440547'
# RUNNING AS USER 'steam' - '1000'
# ARGS:
_______________________________________
Setting up folder and file structure...
Running command 'run' for instance 'main'
2022-10-08 23:57:07: start
2022-10-08 23:57:07: Running /app/server/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?SessionName=blakebot\?ServerPassword=*\?ServerAdminPassword=*\?MaxPlayers=20\?OverrideOfficialDifficulty=5.0\?GameModIds\?GameModIds\?Port=7777\?QueryPort=27015\?RCONEnabled=True\?RCONPort=27020\?listen -log -log
2022-10-08 23:57:07: Server PID: 69
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
2022-10-08 23:57:28: server is up
```

I'm willing to provide other info as needed.

**Comment by BlakeNoel** [comment]
bump

**Comment by Tander** [comment]
same issue when trying to stop server

**Comment by Gornoka** [comment]
> same issue when trying to stop server

if you want to stop the container you have 2 options:

1. stop the container using docker
  if you deploy your docker containers with docker compose you can use 
  'docker compose stop' to stop the servers, on my ark cluster we use this and we 
  never had problems with that approach.
2. stop the server gracefully with arkservermanager
  exec into the running container interactively and stop it using arkservermanger like 'sudo docker exec -it your_container_id bash', then you have an interactive shell within the container and can execute everything as if you had a local install.

For updating the servers we normally just stop the stack and restart it, the image then pulls the latest version automatically.

**Comment by thmhoag** [comment]
Based on the original description, this issue is not with my image. 

> docker run -d \
  --name $ARK \
  -v /home/bnoel/docker_volumes/ark3:/app \
  -v /home/bnoel/docker_volumes/ark3_backups:/home/steam/ARK-Backups \
  --restart always \
  -p 27015:27015/udp \
  -p 7777:7777/udp \
  -p 7778:7778/udp \
  -e SESSION_NAME=blakebot \
  -e SERVER_PASSWORD=* \
  -e ADMIN_PASSWORD=* \
  hermsi/ark-server:latest
  
  `hermsi/ark-server:latest` is someone else's image.
