### ISSUE TITLE
Crossplay with epic games version

### ISSUE THREAD

**Issue by domano** [thmhoag/arkserver#8]
## Image Setup Details

* **Image Tag**: latest

* **Docker Host OS**: linux, Ubuntu 18.04

* **`docker run -v steam:/opt/ark/steam -v ark:/opt/ark/server -p 27015:27015 -p 27015:27015/udp -p 7778:7778 -p 7778:7778/udp -p 7777:7777 -p 7777:7777/udp -e am_ark_SessionName=Dengland -e am_ark_ServerAdminPassword="secret :)" -e am_ark_ServerPasswort="secret :)" --restart=always -d thmhoag/arkserver` 
## Description of Issue

My friend can not join using the epic game store version of ark. Probably the -crossplay parameter needs to be passed, but i could not figure a way out to do so.
Connecting via Steam works.

**Comment by thmhoag** [comment]
Fascinating. Had no idea ARK was in the Epic Game store now. I believe you need either one or both of the following flags to be set:

* `-crossplay`
* `-epiconly`

You can set flags on this image by using an environment variable with the prefix `am_arkflag_<optname>=<anything>`. 

So you might try with one or both of the flags I listed above, like this:

* `-e am_arkflag_crossplay=""`
* `-e am_arkflag_epiconly=""`

I'm not sure if the `-epiconly` flag is actually required. Unfortunately, I don't have a copy of the EpicGames version of ARK to test with, but I'd love to hear back on whether or not this works for you.

Also, just a tip, your mounts for `steam` and `ark` should look like the following:
* `-v steam:/home/steam/.steam/SteamApps/workshop`
* `-v ark:/ark`


EDIT: Looks like you should only need `-crossplay` based on the patch notes here: https://survivetheark.com/index.php?/forums/topic/388254-pc-patch-notes-client-v31187-server-v31197/

**Comment by jcoker85** [comment]
@thmhoag Just to clarify on this, the flag should be

`-e am_arkflag_crossplay="true"`

not with an empty parameter. I was able to get both Steam and EGS users to connect this way.

**Comment by domano** [comment]
Thank you both :) 

The volumes were just a copy and paste error.

**Comment by thmhoag** [comment]
Thanks for the clarifcation @jcoker85. I'll update the README.md with this info for others to see in the future.
